version: '3'

services:
  laconia:
    image: laconia:latest
    ports:
      - 8080:8080
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis-data:/data

volumes:
  redis-data:
